#!/bin/bash
# COMPILE & RUN & CLEAN SCRIPT FOR [ CLIENTS ]

line="\n===================================================================================================\n"

ROOT_TO_JAVA="src/main/java/"
JAVA_TO_ROOT="../../../"

GEN_JAVA_DIR="gen-java/"

ARGS="$@"

# LABELS
COMPILING=$line"COMPILING CLIENT..."$line
STARTING=$line"STARTING CLIENT..."$line

# COMMANDS
COMPILE="javac -cp ".:"$JAVA_TO_ROOT"gen-java:/usr/local/Thrift/*" Client.java"
START="java -cp ".:"$JAVA_TO_ROOT"gen-java:/usr/local/Thrift/*" Client $ARGS"

# EXECUTE
if !(test -d $GEN_JAVA_DIR)
then
  ./build-thrift
else
  clear
fi
cd $ROOT_TO_JAVA
(echo -e $COMPILING) && $COMPILE && (echo -e $STARTING) && $START
